import "./globals.css";
import { dir } from "i18next";
import type { Metadata } from "next";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import { languages } from "@wac/app/i18n/settings";
import { PrimeReactProvider} from 'primereact/api';
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primeicons/primeicons.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

interface PropsType {
    children: React.ReactNode;
    params: { lng: string };
}

export const metadata: Metadata = {
    title: "Nutritional Service",
    description: "Generated by nutritional service",
};

export async function generateStaticParams() {
    return languages.map((lng) => ({ lng }));
}

export default function RootLayout({ children, params: { lng } }: PropsType) {
    return (
        <html lang={lng} dir={dir(lng)}>
            <PrimeReactProvider>
                <body className="bg-light">
                    <header>
                        <Navbar lng={lng} />
                    </header>
                    <main className="w-full h-full inline-block z-0 ">{children}</main>
                    <Footer lng={lng} />
                </body>
            </PrimeReactProvider>
        </html>
    );
}
